name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Oder whatever your default branch is (e.g., master, production)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: hochzeits-memory-prod # Your Firebase Project ID
          channelId: live # Deploy to the 'live' channel (your default site)
          
